### ISSUE TITLE
TO-DO List:

### ISSUE THREAD

**Issue by InhyeokYoo** [InhyeokYoo/rag-tutorial#2]
## TO-DO List:
최종 목표 관련

## RAG:
- [ ] Retrieval로 주는 top-k 문서의 최적화: LLM이 생성할 때 필요한 문서의 수를 최적화
  - 프롬프트를 활용할 수도 있을 것으로 보임.
- [ ] RAG에서 사용하기 좋은/적절한 chunking 사이즈를 찾는 방법 (AutoRAG)
- [ ] 메타데이터 활용 (RAG Survey)
- [ ] Multi-hop QA
- [ ] Prompt compression
  - 제목, 소제목 등을 문서 앞에다가 붙여주는 식으로 사용할 수는 있음

## Prompt:
- [ ] Multi-turn 대화
- [ ] Prompting 잘 주는 방법

## Optimization (Advanced)
- [ ] Hybrid Search Exploration
  - lexical, semantic, vector search 등을 조합하여 진행
- [ ] Recursive Retrieval and Query Engine
  - > Recursive retrieval involves acquiring smaller chunks during the initial retrieval phase to capture key semantic meanings. Subsequently, larger chunks containing more contextual information are provided to the LLM in later stages of the process.
- [ ] StepBack-prompt
  - > encourages the LLM to move away from specific instances and engage in reasoning around broader concepts and principles.
- [ ] HyDE (Hypothetical Document Embeddings)
  - > 생성된 답변이 쿼리(query embedding = document embedding)보다 embedding space에서 더 가깝다는 가정으로 진행. 질문에 대해 hypothetical document를 생성한 이후 이와 문서 사이의 거리를 측정하여 활용하는 기법
